first-line: '&2&lVanilla&8&lMC &6Network'
second-line: '&aЛомать чужой софт нам никогда не надоест!'
online-count: '&eIn development'
players:
  - '&aWork in progress!'
  - '&eCome to the server later!'
  - '&cAnd welcome to the module system!'